# Generated by Django 4.1 on 2022-09-08 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=70)),
                ('discription', models.TextField(max_length=140)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imageuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
