# Generated by Django 4.1 on 2022-08-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='listname',
        ),
    ]
