# Generated by Django 4.1 on 2022-09-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='author',
        ),
    ]
