# Generated by Django 4.1 on 2022-09-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_post_delete_image_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='photo',
        ),
    ]
