# Generated by Django 4.1 on 2022-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(max_length=10000),
        ),
    ]
