# Generated by Django 4.1 on 2022-09-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_header_image_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
