# Generated by Django 4.1 on 2022-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
