# Generated by Django 4.1 on 2022-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_post_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
