# Generated by Django 4.1 on 2022-09-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
